In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df=pd.read_excel(r"C:\Users\ankitvishwakarma\Downloads\Financial_Sample.xlsx")

In [10]:
df.shape

(700, 16)

In [11]:
df=df.bfill()

In [12]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [13]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [14]:
df["Gross Sales"].max()

np.float64(1207500.0)

## Encoding

In [15]:
# text dataset (two type)
# Normal text (delhi, noida,etc)
# ordinal text(small, large, medium, xlarge)

In [16]:
df["Discount Band"].unique()

<ArrowStringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

In [17]:
# Encoding types
# 1- Onehot encoding
# 2- Ordinal encoding
# 3- Lable encoding

In [18]:
db=['Low', 'Medium', 'High']

In [19]:
df["Discount Band"]

0       Low
1       Low
2       Low
3       Low
4       Low
       ...
695    High
696    High
697    High
698    High
699    High
Name: Discount Band, Length: 700, dtype: str

In [20]:
df["Discount Band"]= df["Discount Band"].map(lambda val:db.index(val))

In [21]:
df["Discount Band"]

0      0
1      0
2      0
3      0
4      0
      ..
695    2
696    2
697    2
698    2
699    2
Name: Discount Band, Length: 700, dtype: int64

In [22]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\ankitvishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\ankitvishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\ankitvishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\ankitvishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\ankitvishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\ankitvishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
df=pd.read_excel(r"C:\Users\ankitvishwakarma\Downloads\Financial_Sample.xlsx").bfill()

In [24]:
df["Discount Band"]

0       Low
1       Low
2       Low
3       Low
4       Low
       ...
695    High
696    High
697    High
698    High
699    High
Name: Discount Band, Length: 700, dtype: str

#### OrdinalEncoder

In [25]:
from sklearn.preprocessing import OrdinalEncoder

In [27]:
encoder= OrdinalEncoder(categories=[['Low', 'Medium', 'High']])

In [28]:
df["Discount Band"]=encoder.fit_transform(df[["Discount Band"]])

In [29]:
df["Discount Band"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
695    2.0
696    2.0
697    2.0
698    2.0
699    2.0
Name: Discount Band, Length: 700, dtype: float64

In [31]:
df["Country"].unique()

<ArrowStringArray>
['Canada', 'Germany', 'France', 'Mexico', 'United States of America']
Length: 5, dtype: str

In [32]:
df["Country"]= df["Country"].map(lambda val: list(df["Country"].unique()).index(val))

In [33]:
df["Country"]

0      0
1      1
2      2
3      1
4      3
      ..
695    2
696    3
697    3
698    0
699    4
Name: Country, Length: 700, dtype: int64

#### Label Encoder

In [38]:
df=pd.read_excel(r"C:\Users\ankitvishwakarma\Downloads\Financial_Sample.xlsx").bfill()

In [40]:
df.head(5)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,Low,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,Low,888.0,3,15.0,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,Low,2470.0,3,15.0,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
encoder=LabelEncoder()

In [44]:
df["Country"]=encoder.fit_transform(df[["Country"]])

C:\Users\ankitvishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [45]:
df["Country"]

0      0
1      2
2      1
3      2
4      3
      ..
695    1
696    3
697    3
698    0
699    4
Name: Country, Length: 700, dtype: int64

#### OneHot Encoding

In [48]:
df["Segment"].unique()

<ArrowStringArray>
['Government', 'Midmarket', 'Channel Partners', 'Enterprise',
 'Small Business']
Length: 5, dtype: str

In [51]:
def OneHotEncoding(val):
    df[val]=df["Segment"].map(lambda seg:1 if seg==val else 0)

In [52]:
for val in df["Segment"].unique():
    OneHotEncoding(val)

In [54]:
df.shape

(700, 21)

In [55]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,...,Profit,Date,Month Number,Month Name,Year,Government,Midmarket,Channel Partners,Enterprise,Small Business
0,Government,0,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,...,16185.0,2014-01-01,1,January,2014,1,0,0,0,0
1,Government,2,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,...,13210.0,2014-01-01,1,January,2014,1,0,0,0,0
2,Midmarket,1,Carretera,Low,2178.0,3,15.0,32670.0,0.0,32670.0,...,10890.0,2014-06-01,6,June,2014,0,1,0,0,0
3,Midmarket,2,Carretera,Low,888.0,3,15.0,13320.0,0.0,13320.0,...,4440.0,2014-06-01,6,June,2014,0,1,0,0,0
4,Midmarket,3,Carretera,Low,2470.0,3,15.0,37050.0,0.0,37050.0,...,12350.0,2014-06-01,6,June,2014,0,1,0,0,0

In [56]:
df.Product

0      Carretera
1      Carretera
2      Carretera
3      Carretera
4      Carretera
         ...
695     Amarilla
696     Amarilla
697      Montana
698        Paseo
699          VTT
Name: Product, Length: 700, dtype: str

In [57]:
df.Product.unique()

<ArrowStringArray>
['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla']
Length: 6, dtype: str

In [58]:
from
sklearn.preprocessing import OneHotEncoder

In [77]:
encoder=OneHotEncoder(sparse_output=False)

In [78]:
encoded_df=encoder.fit_transform(df[["Product"]])

In [80]:
encoded_df

array([[0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], shape=(700, 6))

In [81]:
encoded_df= pd.DataFrame(encoded_df, columns=encoder.get_feature_names_out())

In [83]:
encoded_df

,Product_Amarilla,Product_Carretera,Product_Montana,Product_Paseo,Product_VTT,Product_Velo
0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...
695,1.0,0.0,0.0,0.0,0.0,0.0
696,1.0,0.0,0.0,0.0,0.0,0.0
697,0.0,0.0,1.0,0.0,0.0,0.0
698,0.0,0.0,0.0,1.0,0.0,0.0
699,0.0,0.0,0.0,0.0,1.0,0.0