### Standardization and Normalization

In [2]:
data={
    "Empid": [ x for x in range(101,111)],
    "Empsalary": [1234,6546,6768,8789,58756,5645,5657,6556,6756,6756]
    
}

In [3]:
import pandas as pd

In [4]:
df=pd.DataFrame(data)

In [5]:
df

   Empid  Empsalary
0    101       1234
1    102       6546
2    103       6768
3    104       8789
4    105      58756
5    106       5645
6    107       5657
7    108       6556
8    109       6756
9    110       6756

In [ ]:
## Standardization
## z=x−μ/σ

In [7]:
df["scalesalary"]= (df["Empsalary"]-df["Empsalary"].mean())/df["Empsalary"].std()

In [8]:
df

   Empid  Empsalary  scalesalary
0    101       1234    -0.603077
1    102       6546    -0.286280
2    103       6768    -0.273041
3    104       8789    -0.152512
4    105      58756     2.827419
5    106       5645    -0.340014
6    107       5657    -0.339298
7    108       6556    -0.285684
8    109       6756    -0.273756
9    110       6756    -0.273756

In [9]:
df.scalesalary.max()

np.float64(2.8274188448714512)

In [10]:
df=df[df.scalesalary<df.scalesalary.max()]

In [11]:
df

   Empid  Empsalary  scalesalary
0    101       1234    -0.603077
1    102       6546    -0.286280
2    103       6768    -0.273041
3    104       8789    -0.152512
5    106       5645    -0.340014
6    107       5657    -0.339298
7    108       6556    -0.285684
8    109       6756    -0.273756
9    110       6756    -0.273756

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
newdf=StandardScaler().fit_transform(df)

In [94]:
newdf

array([[-1.50718998, -2.52916056, -2.52916056],
       [-1.1763434 ,  0.24403519,  0.24403519],
       [-0.84549682,  0.35993306,  0.35993306],
       [-0.51465024,  1.41502128,  1.41502128],
       [ 0.14704292, -0.22634308, -0.22634308],
       [ 0.4778895 , -0.22007833, -0.22007833],
       [ 0.80873608,  0.24925582,  0.24925582],
       [ 1.13958266,  0.35366831,  0.35366831],
       [ 1.47042924,  0.35366831,  0.35366831]])

### Normalization

In [17]:
## z=(x-min)/(max-min)

In [95]:
from sklearn.preprocessing import MinMaxScaler

In [97]:
df=MinMaxScaler().fit_transform(newdf)

In [98]:
df

array([[0.        , 0.        , 0.        ],
       [0.11111111, 0.70311052, 0.70311052],
       [0.22222222, 0.73249504, 0.73249504],
       [0.33333333, 1.        , 1.        ],
       [0.55555556, 0.58385175, 0.58385175],
       [0.66666667, 0.58544011, 0.58544011],
       [0.77777778, 0.70443415, 0.70443415],
       [0.88888889, 0.73090668, 0.73090668],
       [1.        , 0.73090668, 0.73090668]])